import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import FooterContainer from "@/components/layout/footer/FooterContainer";
import NavbarContainer from "@/components/layout/navbar/NavbarContainer";
import SidebarContainer from "@/components/layout/sidebar/SidebarContainer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`} >
        <header>
          <NavbarContainer></NavbarContainer>
        </header>
        <div className="flex">
          {/* <aside className="w-64 bg-gray-100 min-h-screen p-4">
            <SidebarContainer></SidebarContainer>
          </aside> */}
          <main>{children}</main>
        </div>
        
        <FooterContainer></FooterContainer>
      </body>
    </html>
  );
}
